version: '2.1'
services:

  module-demo:
    image: registry.fit2cloud.com/fit2cloud3/module-demo:IMAGE_TAG
    container_name: module-demo
    ports:
      - 8888:8888
    volumes:
      - share-volume:/opt/fit2cloud/share
      - cmp-conf:/opt/fit2cloud/conf
      - cmp-logs:/opt/fit2cloud/logs
      - kube-project:/var/kobe/data/project
    depends_on:
      management-center:
        condition: service_healthy
    mem_limit: 1024m
    networks:
      - cmp-network


