cmp:                                                              
  version: IMAGE_TAG
  logLevel: INFO
mysql:
  host: cmp-mysql
  port: 3306
modules:
  imagePullSecret: registry-fit2cloud-key                          
  imagePullPolicy: Always
  imagePrefix: registry.fit2cloud.com/fit2cloud3/        
  imageTag: IMAGE_TAG
  demo:
    image: module-demo
    replicas: 1
  busybox:
    image: busybox
    imageTag: latest
    imagePullPolicy: IfNotPresent
storage:
  accessModes: ReadWriteMany
